"""Seed data for known_applications table — extracted from soy-uses.md."""

from .models import KnownApplication

KNOWN_APPLICATIONS: list[KnownApplication] = [
    # === ADHESIVES & SEALANTS ===
    KnownApplication(sector="Adhesives & Sealants", derivative="Soy Protein", category="Wood adhesives",
                     product_name="PureBond", manufacturer="Columbia Forest Products",
                     description="Formaldehyde-free soy protein adhesive for hardwood plywood",
                     year_introduced=2005, market_size="$2.3B soy adhesive market by 2028"),
    KnownApplication(sector="Adhesives & Sealants", derivative="Soy Protein", category="Wood adhesives",
                     product_name="Soyad", manufacturer="Solenis",
                     description="Soy flour adhesive with PAE crosslinker for plywood/OSB",
                     year_introduced=2004),
    KnownApplication(sector="Adhesives & Sealants", derivative="Soy Protein", category="Wood adhesives",
                     product_name=None, manufacturer="Heartland BioComposites",
                     description="Soy protein binder for strawboard panels",
                     year_introduced=2001),
    KnownApplication(sector="Adhesives & Sealants", derivative="Soy Meal", category="Wood adhesives",
                     product_name=None, manufacturer=None,
                     description="Soy flour + PAE/epoxy crosslinker system for D4 water resistance in plywood",
                     year_introduced=None),
    KnownApplication(sector="Adhesives & Sealants", derivative="Soy Protein", category="Packaging adhesives",
                     product_name=None, manufacturer=None,
                     description="Soy protein-based laminating adhesives for food packaging",
                     year_introduced=None),
    KnownApplication(sector="Adhesives & Sealants", derivative="Soy Protein", category="Pressure-sensitive adhesives",
                     product_name=None, manufacturer=None,
                     description="Soy protein-based pressure-sensitive adhesives for labels and tapes",
                     year_introduced=None),
    KnownApplication(sector="Adhesives & Sealants", derivative="Dimer Fatty Acids", category="Hot-melt adhesives",
                     product_name=None, manufacturer="Henkel / H.B. Fuller",
                     description="Dimer acid-based reactive hot-melt adhesives for packaging and bookbinding",
                     year_introduced=None),

    # === COATINGS, PAINTS & INKS ===
    KnownApplication(sector="Coatings, Paints & Inks", derivative="Soy Oil", category="Industrial coatings",
                     product_name=None, manufacturer=None,
                     description="Alkyd resin coatings from soy oil — 1.5B+ lbs/yr consumed in US coatings",
                     year_introduced=None, market_size="$7.2B alkyd resin market (2023)"),
    KnownApplication(sector="Coatings, Paints & Inks", derivative="Epoxidized Soybean Oil", category="Industrial coatings",
                     product_name="AESO coating", manufacturer=None,
                     description="Acrylated epoxidized soybean oil for UV-curable coatings",
                     year_introduced=None, market_size="$836M ESBO market (2023)"),
    KnownApplication(sector="Coatings, Paints & Inks", derivative="Soy Oil", category="Printing inks",
                     product_name=None, manufacturer="American Soybean Association",
                     description="SoySeal certified soy-based printing inks — 95% of US newspaper inks",
                     year_introduced=1987, market_size="90-95% US newspaper ink market"),
    KnownApplication(sector="Coatings, Paints & Inks", derivative="Soy Oil", category="Printing inks",
                     product_name="SoySeal", manufacturer="American Soybean Association",
                     description="Certification program for soy ink content in lithographic and heatset inks",
                     year_introduced=1987),
    KnownApplication(sector="Coatings, Paints & Inks", derivative="Soy-based Resins", category="Industrial coatings",
                     product_name=None, manufacturer=None,
                     description="Bio-based polyurethane dispersions from soy polyols for wood and metal coatings",
                     year_introduced=None),
    KnownApplication(sector="Coatings, Paints & Inks", derivative="Soy Oil", category="Wood finishes",
                     product_name=None, manufacturer="Vermont Natural Coatings",
                     description="Soy-based wood floor finish and furniture coatings",
                     year_introduced=2009),
    KnownApplication(sector="Coatings, Paints & Inks", derivative="Soy Oil", category="Architectural coatings",
                     product_name=None, manufacturer=None,
                     description="Soy-modified alkyd latex paints for interior and exterior architectural use",
                     year_introduced=None),

    # === PLASTICS & BIOPLASTICS ===
    KnownApplication(sector="Plastics & Bioplastics", derivative="Soy-based Polyols", category="Polyols & foams",
                     product_name="BiOH", manufacturer="Cargill",
                     description="Soy-based polyols for flexible and rigid polyurethane foams",
                     year_introduced=2008, market_size="$5.27B bio-polyol market by 2028"),
    KnownApplication(sector="Plastics & Bioplastics", derivative="Soy-based Polyols", category="Polyols & foams",
                     product_name="Agrol", manufacturer="BioBased Systems",
                     description="Soy polyol for spray-applied polyurethane foam insulation",
                     year_introduced=2006),
    KnownApplication(sector="Plastics & Bioplastics", derivative="Soy-based Polyols", category="Polyols & foams",
                     product_name="Renuva", manufacturer="Dow (Olin)",
                     description="Natural oil polyol for flexible foam in furniture and automotive seating",
                     year_introduced=2007),
    KnownApplication(sector="Plastics & Bioplastics", derivative="Epoxidized Soybean Oil", category="Plasticizers",
                     product_name=None, manufacturer=None,
                     description="ESBO as PVC plasticizer/stabilizer replacing phthalates — 200K+ tons/yr globally",
                     year_introduced=None, market_size="$836M (2023), $1.2B by 2032"),
    KnownApplication(sector="Plastics & Bioplastics", derivative="Soy Protein", category="Bioplastics",
                     product_name=None, manufacturer="Ford Motor Company / University of Toronto",
                     description="Soy protein plastic composites for automotive parts (Ford heritage from Henry Ford 1941)",
                     year_introduced=1941),
    KnownApplication(sector="Plastics & Bioplastics", derivative="Soy-based Polyols", category="Polyols & foams",
                     product_name=None, manufacturer="Urethane Soy Systems (USS)",
                     description="Soy-based polyol systems for structural insulated panels (SIPs)",
                     year_introduced=2003),
    KnownApplication(sector="Plastics & Bioplastics", derivative="Dimer Fatty Acids", category="Polyamide resins",
                     product_name=None, manufacturer="Croda / BASF",
                     description="Dimer acid-based polyamide hot-melt and reactive adhesives",
                     year_introduced=None),
    KnownApplication(sector="Plastics & Bioplastics", derivative="Azelaic Acid", category="Engineering plastics",
                     product_name=None, manufacturer="Arkema",
                     description="Azelaic acid as monomer for Nylon 6,9 and other long-chain polyamides",
                     year_introduced=None),
    KnownApplication(sector="Plastics & Bioplastics", derivative="Soy Oil", category="Bioplastics",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based polylactic acid (PLA) blend modifiers improving impact strength",
                     year_introduced=None),

    # === LUBRICANTS & METALWORKING FLUIDS ===
    KnownApplication(sector="Lubricants & Metalworking Fluids", derivative="Soy Oil", category="Dielectric fluids",
                     product_name="Envirotemp FR3", manufacturer="Cargill",
                     description="Soy-based natural ester dielectric fluid for power transformers",
                     year_introduced=1998, market_size="$3.5B bio-lubricant market (2025)"),
    KnownApplication(sector="Lubricants & Metalworking Fluids", derivative="Soy Oil", category="Industrial lubricants",
                     product_name="BioSOY", manufacturer="Biosynthetic Technologies",
                     description="Estolide-based lubricants from soy oil with superior cold-flow properties",
                     year_introduced=2012),
    KnownApplication(sector="Lubricants & Metalworking Fluids", derivative="Soy Oil", category="Industrial lubricants",
                     product_name=None, manufacturer=None,
                     description="Soy-based hydraulic fluids for construction and forestry equipment",
                     year_introduced=None),
    KnownApplication(sector="Lubricants & Metalworking Fluids", derivative="Soy Oil", category="Industrial lubricants",
                     product_name=None, manufacturer=None,
                     description="Soy-based chainsaw bar oil and rail flange lubricants for total-loss applications",
                     year_introduced=None),
    KnownApplication(sector="Lubricants & Metalworking Fluids", derivative="Soy Oil", category="Metalworking",
                     product_name=None, manufacturer=None,
                     description="Soy-based metalworking fluids, quenchants, and mold release agents",
                     year_introduced=None),
    KnownApplication(sector="Lubricants & Metalworking Fluids", derivative="Soy Oil", category="Two-cycle oil",
                     product_name=None, manufacturer=None,
                     description="Soy-based two-cycle engine oil for marine outboard and small engines",
                     year_introduced=None),
    KnownApplication(sector="Lubricants & Metalworking Fluids", derivative="Soy Oil", category="Gear oils",
                     product_name=None, manufacturer="Renewable Lubricants",
                     description="Soy-based gear and compressor oils meeting AGMA specifications",
                     year_introduced=2005),
    KnownApplication(sector="Lubricants & Metalworking Fluids", derivative="Soy Oil", category="Greases",
                     product_name=None, manufacturer=None,
                     description="Soy-based lithium complex greases for industrial bearing lubrication",
                     year_introduced=None),

    # === ENERGY & BIOFUELS ===
    KnownApplication(sector="Energy & Biofuels", derivative="Soy Oil", category="Biodiesel",
                     product_name="FAME biodiesel", manufacturer=None,
                     description="Soy oil FAME biodiesel — soy is #1 US biodiesel feedstock",
                     year_introduced=1992, market_size="$56.5B global biodiesel market (2024)"),
    KnownApplication(sector="Energy & Biofuels", derivative="Soy Oil", category="Renewable diesel",
                     product_name=None, manufacturer="Diamond Green Diesel / Neste / Marathon",
                     description="Hydrotreated vegetable oil (HVO) renewable diesel from soy oil",
                     year_introduced=2013, market_size="$61.8B by 2030"),
    KnownApplication(sector="Energy & Biofuels", derivative="Soy Oil", category="Sustainable aviation fuel",
                     product_name="SAF", manufacturer="World Energy / Neste",
                     description="HEFA-SPK sustainable aviation fuel from soy oil via hydroprocessing",
                     year_introduced=2016),
    KnownApplication(sector="Energy & Biofuels", derivative="Glycerol soy-derived", category="Glycerin byproducts",
                     product_name=None, manufacturer=None,
                     description="Crude glycerin from biodiesel converted to propylene glycol, epichlorohydrin",
                     year_introduced=None),
    KnownApplication(sector="Energy & Biofuels", derivative="Soy Oil", category="Biodiesel",
                     product_name="B20", manufacturer="Various blenders",
                     description="20% soy biodiesel blend — most common commercial biodiesel concentration in US",
                     year_introduced=2002),
    KnownApplication(sector="Energy & Biofuels", derivative="Soy Oil", category="Biodiesel",
                     product_name="B100", manufacturer="Various producers",
                     description="Neat (100%) soy biodiesel for off-road and marine diesel engines",
                     year_introduced=None),
    KnownApplication(sector="Energy & Biofuels", derivative="Soy Oil", category="Renewable diesel",
                     product_name=None, manufacturer=None,
                     description="Co-processed soy oil in petroleum refinery hydrotreaters for drop-in renewable diesel",
                     year_introduced=2010),

    # === CONSTRUCTION & BUILDING MATERIALS ===
    KnownApplication(sector="Construction & Building Materials", derivative="Soy-based Polyols", category="Spray foam insulation",
                     product_name="SoyTherm", manufacturer=None,
                     description="Soy polyol spray foam insulation for residential and commercial buildings",
                     year_introduced=2005),
    KnownApplication(sector="Construction & Building Materials", derivative="Soy Oil", category="Concrete treatments",
                     product_name="PoreShield", manufacturer="Purdue/ISU license",
                     description="Soy methyl ester polystyrene (SME-PS) concrete sealant penetrating 5x deeper than silane",
                     year_introduced=2015),
    KnownApplication(sector="Construction & Building Materials", derivative="Methyl Soyate", category="Asphalt",
                     product_name=None, manufacturer=None,
                     description="Soy-based asphalt rejuvenator for recycled asphalt pavement (RAP) — extends road life",
                     year_introduced=None),
    KnownApplication(sector="Construction & Building Materials", derivative="Soy Oil", category="Dust control",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based dust suppressant for gravel roads and construction sites",
                     year_introduced=None),
    KnownApplication(sector="Construction & Building Materials", derivative="Soy Protein", category="Wood composites",
                     product_name=None, manufacturer=None,
                     description="Soy protein adhesive for oriented strand board (OSB) and medium-density fiberboard (MDF)",
                     year_introduced=None),
    KnownApplication(sector="Construction & Building Materials", derivative="Soy-based Polyols", category="Insulation",
                     product_name=None, manufacturer="Demilec / BASF",
                     description="Soy polyol closed-cell spray foam insulation with R-6.5/inch",
                     year_introduced=2008),
    KnownApplication(sector="Construction & Building Materials", derivative="Soy Fiber", category="Composites",
                     product_name=None, manufacturer=None,
                     description="Soy hull fiber in wood-plastic composite decking and fencing",
                     year_introduced=None),
    KnownApplication(sector="Construction & Building Materials", derivative="Soy Oil", category="Concrete form release",
                     product_name=None, manufacturer=None,
                     description="Soy-based concrete form release agents replacing petroleum oils",
                     year_introduced=None),

    # === RUBBER & ELASTOMERS ===
    KnownApplication(sector="Rubber & Elastomers", derivative="Soy Oil", category="Tires",
                     product_name="Assurance WeatherReady", manufacturer="Goodyear",
                     description="Soy oil tire tread compound improving wet grip and tread life",
                     year_introduced=2017),
    KnownApplication(sector="Rubber & Elastomers", derivative="Soy Oil", category="Tires",
                     product_name="Eagle F1 SuperSport", manufacturer="Goodyear",
                     description="Performance tire with soy oil rubber compound",
                     year_introduced=2020),
    KnownApplication(sector="Rubber & Elastomers", derivative="Soy Oil", category="Processing oil",
                     product_name=None, manufacturer=None,
                     description="Soy oil as TDAE/aromatic oil replacement in rubber — lowers Tg, improves wet traction",
                     year_introduced=None, market_size="$2.1B bio-rubber market by 2028"),
    KnownApplication(sector="Rubber & Elastomers", derivative="Epoxidized Soybean Oil", category="Processing oil",
                     product_name=None, manufacturer=None,
                     description="ESBO as rubber plasticizer compatible with silica-reinforced compounds",
                     year_introduced=None),
    KnownApplication(sector="Rubber & Elastomers", derivative="Soy Oil", category="Tires",
                     product_name=None, manufacturer="Kumho / Continental",
                     description="Soy oil in eco-tire formulations for reduced rolling resistance",
                     year_introduced=2019),
    KnownApplication(sector="Rubber & Elastomers", derivative="Soy Oil", category="Rubber goods",
                     product_name=None, manufacturer=None,
                     description="Soy oil in industrial rubber hose, belt, and gasket compounds",
                     year_introduced=None),

    # === TEXTILES & FIBERS ===
    KnownApplication(sector="Textiles & Fibers", derivative="Soy Protein", category="Soy protein fiber",
                     product_name="SPF", manufacturer="Shanghai Winshow / Swicofil",
                     description="Soy protein fiber (SPF) — 'vegetable cashmere' with antimicrobial properties",
                     year_introduced=2003),
    KnownApplication(sector="Textiles & Fibers", derivative="Soy Protein", category="Soy protein fiber",
                     product_name=None, manufacturer=None,
                     description="Soy fiber blends with cotton/Tencel for apparel and home textiles",
                     year_introduced=None),
    KnownApplication(sector="Textiles & Fibers", derivative="Soy Fiber", category="Composites",
                     product_name=None, manufacturer=None,
                     description="Soy hull fiber as reinforcement in natural fiber polymer composites (NFPCs)",
                     year_introduced=None),
    KnownApplication(sector="Textiles & Fibers", derivative="Soy Oil", category="Textile finishing",
                     product_name=None, manufacturer=None,
                     description="Epoxidized soy oil as textile softener and finishing agent",
                     year_introduced=None),
    KnownApplication(sector="Textiles & Fibers", derivative="Soy Protein", category="Nonwovens",
                     product_name=None, manufacturer=None,
                     description="Soy protein binder for nonwoven fabrics in filtration and geotextiles",
                     year_introduced=None),

    # === CHEMICALS & SOLVENTS ===
    KnownApplication(sector="Chemicals & Solvents", derivative="Methyl Soyate", category="Bio-solvents",
                     product_name="SoyGold", manufacturer="AG Environmental Products",
                     description="Methyl soyate industrial solvent for parts washing, paint stripping, ink cleaning",
                     year_introduced=1995, market_size="$1.64B methyl soyate market by 2030"),
    KnownApplication(sector="Chemicals & Solvents", derivative="Methyl Soyate", category="Bio-solvents",
                     product_name="VertecBio Gold", manufacturer="Vertec BioSolvents",
                     description="High-purity methyl soyate solvent replacing mineral spirits, MEK, and acetone",
                     year_introduced=2002),
    KnownApplication(sector="Chemicals & Solvents", derivative="Azelaic Acid", category="Chemical intermediates",
                     product_name=None, manufacturer="Emery Oleochemicals / Matrica",
                     description="Azelaic acid (nonanedioic acid) from soy oil ozonolysis for nylon, plasticizers, lubricants",
                     year_introduced=None, market_size="$929M (2024)"),
    KnownApplication(sector="Chemicals & Solvents", derivative="Dimer Fatty Acids", category="Chemical intermediates",
                     product_name=None, manufacturer="Croda / Kraton / Arizona Chemical",
                     description="Dimer fatty acids from soy for polyamide hot-melt adhesives, printing inks, corrosion inhibitors",
                     year_introduced=None, market_size="$823M (2025)"),
    KnownApplication(sector="Chemicals & Solvents", derivative="Soy Fatty Acids", category="Oleochemicals",
                     product_name=None, manufacturer=None,
                     description="Soy fatty acid fractionation for surfactants, alkyd resins, and rubber chemicals",
                     year_introduced=None),
    KnownApplication(sector="Chemicals & Solvents", derivative="Soy Lecithin", category="Emulsifiers",
                     product_name=None, manufacturer="Cargill / ADM / Bunge",
                     description="Industrial soy lecithin as emulsifier, release agent, and wetting agent",
                     year_introduced=None),
    KnownApplication(sector="Chemicals & Solvents", derivative="Soy Molasses", category="Fermentation",
                     product_name=None, manufacturer=None,
                     description="Soy molasses (SPC byproduct) as carbon source for ethanol, citric acid, and enzyme fermentation",
                     year_introduced=None),
    KnownApplication(sector="Chemicals & Solvents", derivative="Glycerol soy-derived", category="Chemical intermediates",
                     product_name=None, manufacturer="Solvay / Dow",
                     description="Bio-glycerol from soy biodiesel converted to epichlorohydrin and propylene glycol",
                     year_introduced=2007),
    KnownApplication(sector="Chemicals & Solvents", derivative="Methyl Soyate", category="Paint strippers",
                     product_name="SoyStrip", manufacturer="Franmar Chemical",
                     description="Soy-based paint and coating remover replacing methylene chloride strippers",
                     year_introduced=1997),
    KnownApplication(sector="Chemicals & Solvents", derivative="Soy Oil", category="Polyols",
                     product_name=None, manufacturer=None,
                     description="Soy oil ring-opening for production of bio-based polyether polyols",
                     year_introduced=None),
    KnownApplication(sector="Chemicals & Solvents", derivative="Soy Fatty Acids", category="Surfactants",
                     product_name=None, manufacturer=None,
                     description="Soy-derived fatty acid ethoxylates as nonionic surfactants for industrial and household use",
                     year_introduced=None),

    # === PERSONAL CARE & COSMETICS ===
    KnownApplication(sector="Personal Care & Cosmetics", derivative="Soy Oil", category="Skin care",
                     product_name="Aveeno", manufacturer="Johnson & Johnson",
                     description="Soy-based skin care products with soy isoflavones for anti-aging",
                     year_introduced=2004),
    KnownApplication(sector="Personal Care & Cosmetics", derivative="Soy Isoflavones", category="Anti-aging",
                     product_name=None, manufacturer=None,
                     description="Soy isoflavones (genistein, daidzein) in cosmetics for skin elasticity and hyperpigmentation",
                     year_introduced=None),
    KnownApplication(sector="Personal Care & Cosmetics", derivative="Soy Oil", category="Hair care",
                     product_name=None, manufacturer=None,
                     description="Hydrolyzed soy protein in shampoos and conditioners for hair strengthening",
                     year_introduced=None),
    KnownApplication(sector="Personal Care & Cosmetics", derivative="Glycerol soy-derived", category="Moisturizers",
                     product_name=None, manufacturer=None,
                     description="Soy-derived glycerin as humectant in lotions, creams, and soaps",
                     year_introduced=None),
    KnownApplication(sector="Personal Care & Cosmetics", derivative="Soy Lecithin", category="Emulsifiers",
                     product_name=None, manufacturer=None,
                     description="Soy lecithin as natural emulsifier in creams, lotions, and lip products",
                     year_introduced=None),
    KnownApplication(sector="Personal Care & Cosmetics", derivative="Soy Wax", category="Lip care",
                     product_name=None, manufacturer=None,
                     description="Soy wax in natural lip balms and lipsticks as petroleum wax replacement",
                     year_introduced=None),
    KnownApplication(sector="Personal Care & Cosmetics", derivative="Soy Oil", category="Body care",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based massage oils and body washes for sensitive skin",
                     year_introduced=None),

    # === CLEANING PRODUCTS & SURFACTANTS ===
    KnownApplication(sector="Cleaning Products & Surfactants", derivative="Methyl Soyate", category="Industrial cleaners",
                     product_name="BioSoy", manufacturer="Gemtek",
                     description="Methyl soyate degreaser for industrial and institutional cleaning",
                     year_introduced=2000),
    KnownApplication(sector="Cleaning Products & Surfactants", derivative="Soy Fatty Acids", category="Surfactants",
                     product_name=None, manufacturer=None,
                     description="Methyl ester sulfonates (MES) from soy for laundry detergent surfactants",
                     year_introduced=None),
    KnownApplication(sector="Cleaning Products & Surfactants", derivative="Soy Oil", category="Hand cleaners",
                     product_name=None, manufacturer=None,
                     description="Soy-based waterless hand cleaners replacing petroleum solvents",
                     year_introduced=None),
    KnownApplication(sector="Cleaning Products & Surfactants", derivative="Methyl Soyate", category="Parts washers",
                     product_name=None, manufacturer=None,
                     description="Methyl soyate in automated parts washer fluid replacing chlorinated solvents",
                     year_introduced=None),
    KnownApplication(sector="Cleaning Products & Surfactants", derivative="Soy Oil", category="Floor cleaners",
                     product_name=None, manufacturer=None,
                     description="Soy-based floor strippers and cleaners for commercial janitorial use",
                     year_introduced=None),

    # === AGRICULTURE ===
    KnownApplication(sector="Agriculture", derivative="Methyl Soyate", category="Spray adjuvants",
                     product_name=None, manufacturer=None,
                     description="Methylated seed oil (MSO) spray adjuvant improving herbicide efficacy by 20-30%",
                     year_introduced=None),
    KnownApplication(sector="Agriculture", derivative="Soy Oil", category="Crop oil concentrate",
                     product_name=None, manufacturer=None,
                     description="Soy-based crop oil concentrate (COC) as pesticide carrier and spreader",
                     year_introduced=None),
    KnownApplication(sector="Agriculture", derivative="Soy Meal", category="Animal feed",
                     product_name=None, manufacturer=None,
                     description="Soy meal in aquaculture and livestock feed — 97% of US soy meal used as feed",
                     year_introduced=None, market_size="$82B global soy meal market"),
    KnownApplication(sector="Agriculture", derivative="Soy Hulls", category="Feed supplements",
                     product_name=None, manufacturer=None,
                     description="Soy hulls as digestible fiber supplement for ruminant and equine feed",
                     year_introduced=None),
    KnownApplication(sector="Agriculture", derivative="Soy Oil", category="Dust control",
                     product_name=None, manufacturer=None,
                     description="Soy oil as grain dust suppressant in elevators and storage facilities",
                     year_introduced=None),
    KnownApplication(sector="Agriculture", derivative="Soy Oil", category="Biopesticides",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based horticultural spray oils for organic pest management",
                     year_introduced=None),
    KnownApplication(sector="Agriculture", derivative="Soy Protein", category="Seed coatings",
                     product_name=None, manufacturer=None,
                     description="Soy protein-based seed coating binders for improved germination and nutrient delivery",
                     year_introduced=None),

    # === PACKAGING & CONTAINERS ===
    KnownApplication(sector="Packaging & Containers", derivative="Soy-based Polyols", category="Foam packaging",
                     product_name=None, manufacturer="Sealed Air / StarchTech",
                     description="Soy-based loose-fill packaging peanuts and cushioning foam",
                     year_introduced=2000),
    KnownApplication(sector="Packaging & Containers", derivative="Soy Protein", category="Edible films",
                     product_name=None, manufacturer=None,
                     description="Soy protein isolate edible films and coatings for food packaging",
                     year_introduced=None),
    KnownApplication(sector="Packaging & Containers", derivative="Soy Wax", category="Paper coatings",
                     product_name=None, manufacturer=None,
                     description="Soy wax coatings for corrugated containers replacing petroleum wax",
                     year_introduced=None),
    KnownApplication(sector="Packaging & Containers", derivative="Soy Oil", category="Biodegradable packaging",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based polyurethane films for biodegradable flexible food packaging",
                     year_introduced=None),

    # === ELECTRONICS ===
    KnownApplication(sector="Electronics", derivative="Soy Oil", category="Dielectric fluids",
                     product_name="Envirotemp FR3", manufacturer="Cargill",
                     description="Natural ester transformer fluid — installed in 3M+ transformers globally",
                     year_introduced=1998, market_size="Part of $3.5B bio-lubricant market"),
    KnownApplication(sector="Electronics", derivative="Soy-based Resins", category="Circuit boards",
                     product_name=None, manufacturer=None,
                     description="Soy-based epoxy resins for printed circuit board laminates",
                     year_introduced=None),
    KnownApplication(sector="Electronics", derivative="Soy-based Resins", category="Encapsulants",
                     product_name=None, manufacturer=None,
                     description="Bio-based soy resin potting compounds for electronic component protection",
                     year_introduced=None),

    # === FIREFIGHTING FOAM ===
    KnownApplication(sector="Firefighting Foam", derivative="Soy Protein", category="Fluorine-free foam",
                     product_name=None, manufacturer="Bio-Ex / Solberg / National Foam",
                     description="Soy protein-based fluorine-free firefighting foam as AFFF/PFAS replacement",
                     year_introduced=2018),
    KnownApplication(sector="Firefighting Foam", derivative="Soy Protein", category="Fluorine-free foam",
                     product_name="Re-Healing Foam", manufacturer="Bio-Ex",
                     description="Next-gen soy-protein firefighting foam meeting MIL-PRF performance specs",
                     year_introduced=2020),

    # === AUTOMOTIVE & TRANSPORTATION ===
    KnownApplication(sector="Automotive & Transportation", derivative="Soy-based Polyols", category="Automotive foams",
                     product_name=None, manufacturer="Ford Motor Company",
                     description="Soy polyol seating foam in Ford vehicles — 5M+ vehicles with soy foam seats",
                     year_introduced=2008),
    KnownApplication(sector="Automotive & Transportation", derivative="Soy-based Polyols", category="Automotive foams",
                     product_name=None, manufacturer="Ford Motor Company",
                     description="Soy foam in headliners, armrests, door panels, and trunk liners",
                     year_introduced=2011),
    KnownApplication(sector="Automotive & Transportation", derivative="Soy Oil", category="Automotive rubber",
                     product_name=None, manufacturer="Goodyear / Bridgestone",
                     description="Soy oil in tire tread compounds for improved wet performance",
                     year_introduced=2017),
    KnownApplication(sector="Automotive & Transportation", derivative="Soy Oil", category="Lubricants",
                     product_name=None, manufacturer=None,
                     description="Soy-based engine oils and transmission fluids for fleet vehicles",
                     year_introduced=None),
    KnownApplication(sector="Automotive & Transportation", derivative="Soy-based Polyols", category="Sound dampening",
                     product_name=None, manufacturer=None,
                     description="Soy polyol viscoelastic foams for automotive NVH (noise, vibration, harshness) dampening",
                     year_introduced=None),

    # === PHARMACEUTICALS & MEDICAL ===
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Oil", category="Parenteral nutrition",
                     product_name="Intralipid", manufacturer="Fresenius Kabi",
                     description="Soy oil-based IV fat emulsion for parenteral nutrition — gold standard since 1962",
                     year_introduced=1962),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Oil", category="Parenteral nutrition",
                     product_name="Liposyn", manufacturer="Hospira (Pfizer)",
                     description="Soy oil-based IV lipid emulsion for clinical nutrition",
                     year_introduced=1975),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Lecithin", category="Drug delivery",
                     product_name=None, manufacturer=None,
                     description="Soy lecithin phospholipids in liposomal drug delivery (Doxil, AmBisome)",
                     year_introduced=1995),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Lecithin", category="Drug delivery",
                     product_name=None, manufacturer="BioNTech / Moderna",
                     description="Soy-derived lipid nanoparticles in mRNA vaccine delivery systems",
                     year_introduced=2020),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Phytosterols", category="Steroid synthesis",
                     product_name=None, manufacturer="BASF / Raisio",
                     description="Stigmasterol from soy as precursor for progesterone, cortisone, and other steroids",
                     year_introduced=1940, market_size="$1.1B phytosterol market (2025)"),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Phytosterols", category="Nutraceuticals",
                     product_name="Benecol", manufacturer="Raisio",
                     description="Phytosterol/stanol esters from soy for cholesterol-lowering functional foods",
                     year_introduced=1995),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Isoflavones", category="Nutraceuticals",
                     product_name=None, manufacturer=None,
                     description="Soy isoflavone supplements for menopausal symptoms and bone health",
                     year_introduced=None, market_size="$1.2B global isoflavone market"),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Oil", category="Excipients",
                     product_name=None, manufacturer=None,
                     description="Refined soy oil as carrier/excipient in soft gelatin capsules and oral formulations",
                     year_introduced=None),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Oil", category="Anesthesia",
                     product_name="Diprivan (Propofol)", manufacturer="Fresenius Kabi",
                     description="Propofol IV anesthetic formulated in soy oil emulsion",
                     year_introduced=1989),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Lecithin", category="Excipients",
                     product_name=None, manufacturer=None,
                     description="Soy lecithin as emulsifier in parenteral and topical pharmaceutical formulations",
                     year_introduced=None),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Protein", category="Wound care",
                     product_name=None, manufacturer=None,
                     description="Soy protein-based wound dressing films with antimicrobial properties",
                     year_introduced=None),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Oil", category="Diagnostic imaging",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based contrast agent carriers for ultrasound imaging",
                     year_introduced=None),

    # === CANDLES & HOME PRODUCTS ===
    KnownApplication(sector="Candles & Home Products", derivative="Soy Wax", category="Candle wax",
                     product_name="NatureWax C-3", manufacturer="Cargill",
                     description="Container blend soy wax — dominates natural candle wax market",
                     year_introduced=2003, market_size="$5.7B soy wax candle market (2023)"),
    KnownApplication(sector="Candles & Home Products", derivative="Soy Wax", category="Candle wax",
                     product_name="NatureWax C-6", manufacturer="Cargill",
                     description="Soy wax blend for pillar and votive candles",
                     year_introduced=2005),
    KnownApplication(sector="Candles & Home Products", derivative="Soy Wax", category="Candle wax",
                     product_name="Golden Brands 464", manufacturer="AAK",
                     description="Premium container soy wax for candle making",
                     year_introduced=2006),
    KnownApplication(sector="Candles & Home Products", derivative="Soy Wax", category="Wax melts",
                     product_name=None, manufacturer=None,
                     description="Soy wax melts and tarts for electric warmers and home fragrance",
                     year_introduced=None),
    KnownApplication(sector="Candles & Home Products", derivative="Soy Wax", category="Wax coatings",
                     product_name=None, manufacturer=None,
                     description="Soy wax coatings for cheese wheels, produce, and food preservation",
                     year_introduced=None),
    KnownApplication(sector="Candles & Home Products", derivative="Soy Wax", category="Candle wax",
                     product_name="EcoSoya", manufacturer="NGI International",
                     description="100% soy container wax for artisan candle makers",
                     year_introduced=2004),
    KnownApplication(sector="Candles & Home Products", derivative="Soy Wax", category="Candle wax",
                     product_name=None, manufacturer="Yankee Candle / Bath & Body Works",
                     description="Major candle brands using soy wax blends in retail candle lines",
                     year_introduced=2010),
    KnownApplication(sector="Candles & Home Products", derivative="Soy Wax", category="Fire starters",
                     product_name=None, manufacturer=None,
                     description="Soy wax fire starters and kindling cubes for fireplaces and camping",
                     year_introduced=None),

    # === PAPER & PRINTING ===
    KnownApplication(sector="Paper & Printing", derivative="Soy Oil", category="Printing inks",
                     product_name="SoySeal ink", manufacturer="Various (ASA certified)",
                     description="Soy-based printing inks used in 95% of US daily newspapers",
                     year_introduced=1987),
    KnownApplication(sector="Paper & Printing", derivative="Soy Oil", category="Printing inks",
                     product_name=None, manufacturer=None,
                     description="Soy-based heatset and sheetfed offset inks for magazines and catalogs",
                     year_introduced=None),
    KnownApplication(sector="Paper & Printing", derivative="Soy Protein", category="Paper coatings",
                     product_name=None, manufacturer=None,
                     description="Soy protein isolate as paper coating binder replacing casein",
                     year_introduced=None),
    KnownApplication(sector="Paper & Printing", derivative="Soy Protein", category="Paper coatings",
                     product_name=None, manufacturer=None,
                     description="Soy protein wet-strength agents for paper towels and tissue",
                     year_introduced=None),
    KnownApplication(sector="Paper & Printing", derivative="Soy Wax", category="Paper treatments",
                     product_name=None, manufacturer=None,
                     description="Soy wax as corrugated board coating replacing petroleum wax",
                     year_introduced=None),
    KnownApplication(sector="Paper & Printing", derivative="Soy Oil", category="De-inking",
                     product_name=None, manufacturer=None,
                     description="Soy-based de-inking agents for recycled paper processing — soy inks easier to remove",
                     year_introduced=None),
    KnownApplication(sector="Paper & Printing", derivative="Soy Oil", category="Ink formulation",
                     product_name=None, manufacturer=None,
                     description="Soy oil in flexographic inks for corrugated box printing — lower VOC than petroleum inks",
                     year_introduced=None),
    KnownApplication(sector="Paper & Printing", derivative="Soy Oil", category="Toner",
                     product_name=None, manufacturer=None,
                     description="Soy-based toner particles for laser printers and copiers with improved fusing",
                     year_introduced=None),

    # === WATER TREATMENT (NEW SECTOR) ===
    KnownApplication(sector="Water Treatment", derivative="Soy Protein", category="Flocculants",
                     product_name=None, manufacturer=None,
                     description="Soy protein-based flocculants for turbidity removal in municipal water treatment",
                     year_introduced=None),
    KnownApplication(sector="Water Treatment", derivative="Soy Hulls", category="Adsorbents",
                     product_name=None, manufacturer=None,
                     description="Soy hull-derived activated carbon for heavy metal adsorption in wastewater",
                     year_introduced=None),
    KnownApplication(sector="Water Treatment", derivative="Soy Oil", category="Oil spill remediation",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based bioremediation surfactants for oil spill cleanup",
                     year_introduced=None),

    # === 3D PRINTING & ADDITIVE MANUFACTURING (NEW SECTOR) ===
    KnownApplication(sector="3D Printing & Additive Manufacturing", derivative="Soy Oil", category="Photopolymers",
                     product_name=None, manufacturer=None,
                     description="Acrylated soybean oil as renewable monomer in UV-curable 3D printing resins",
                     year_introduced=2018),
    KnownApplication(sector="3D Printing & Additive Manufacturing", derivative="Soy-based Polyols", category="Filaments",
                     product_name=None, manufacturer=None,
                     description="Soy polyol-based thermoplastic polyurethane filaments for FDM 3D printing",
                     year_introduced=None),

    # === MINING & MINERAL PROCESSING (NEW SECTOR) ===
    KnownApplication(sector="Mining & Mineral Processing", derivative="Soy Fatty Acids", category="Froth flotation",
                     product_name=None, manufacturer=None,
                     description="Soy fatty acid collectors for froth flotation separation of iron ore and phosphate minerals",
                     year_introduced=None),
    KnownApplication(sector="Mining & Mineral Processing", derivative="Methyl Soyate", category="Dust suppression",
                     product_name=None, manufacturer=None,
                     description="Methyl soyate dust suppressant for open-pit mining operations",
                     year_introduced=None),

    # === COMPOSITES & ADVANCED MATERIALS (NEW SECTOR) ===
    KnownApplication(sector="Composites & Advanced Materials", derivative="Soy Oil", category="Thermoset resins",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based vinyl ester resins for fiberglass-reinforced composites",
                     year_introduced=None),
    KnownApplication(sector="Composites & Advanced Materials", derivative="Soy Protein", category="Bio-composites",
                     product_name=None, manufacturer=None,
                     description="Soy protein isolate as matrix binder in natural fiber-reinforced bio-composites",
                     year_introduced=None),
    KnownApplication(sector="Composites & Advanced Materials", derivative="Epoxidized Soybean Oil", category="Thermoset resins",
                     product_name=None, manufacturer=None,
                     description="ESBO-based epoxy thermoset resins for wind turbine blade composites",
                     year_introduced=None),
    KnownApplication(sector="Composites & Advanced Materials", derivative="Soy-based Resins", category="Bio-composites",
                     product_name=None, manufacturer="John Deere / Ashland",
                     description="Soy-based sheet molding compound (SMC) panels for agricultural equipment",
                     year_introduced=2003),

    # === OILFIELD & DRILLING (NEW SECTOR) ===
    KnownApplication(sector="Oilfield & Drilling", derivative="Soy Lecithin", category="Drilling fluids",
                     product_name=None, manufacturer=None,
                     description="Soy lecithin as emulsifier and lubricity additive in water-based drilling muds",
                     year_introduced=None),
    KnownApplication(sector="Oilfield & Drilling", derivative="Methyl Soyate", category="Well stimulation",
                     product_name=None, manufacturer=None,
                     description="Methyl soyate as bio-based solvent in well stimulation and paraffin removal",
                     year_introduced=None),

    # === MARINE & WATERCRAFT (NEW SECTOR) ===
    KnownApplication(sector="Marine & Watercraft", derivative="Soy Oil", category="Antifouling coatings",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based antifouling marine coatings to prevent barnacle and algae attachment",
                     year_introduced=None),
    KnownApplication(sector="Marine & Watercraft", derivative="Soy Oil", category="Marine lubricants",
                     product_name=None, manufacturer=None,
                     description="Soy-based stern tube lubricants and hydraulic fluids for environmentally sensitive waterways",
                     year_introduced=None),

    # === PET CARE (NEW SECTOR) ===
    KnownApplication(sector="Pet Care", derivative="Soy Hulls", category="Cat litter",
                     product_name=None, manufacturer=None,
                     description="Soy hull-based clumping cat litter — biodegradable and flushable",
                     year_introduced=2005),
    KnownApplication(sector="Pet Care", derivative="Soy Wax", category="Pet products",
                     product_name=None, manufacturer=None,
                     description="Soy wax-based paw balm and nose balm for dogs",
                     year_introduced=None),

    # === ADDITIONAL ENTRIES TO REACH 150+ ===
    KnownApplication(sector="Adhesives & Sealants", derivative="Soy Protein", category="Construction sealants",
                     product_name=None, manufacturer=None,
                     description="Soy protein-based caulks and sealants for window and door frame sealing",
                     year_introduced=None),
    KnownApplication(sector="Energy & Biofuels", derivative="Soy Oil", category="Marine fuel",
                     product_name=None, manufacturer=None,
                     description="Soy-derived biofuel blends for IMO 2020-compliant marine fuel applications",
                     year_introduced=2020),
    KnownApplication(sector="Rubber & Elastomers", derivative="Soy Oil", category="Footwear",
                     product_name=None, manufacturer=None,
                     description="Soy oil in rubber outsole compounds for athletic and casual footwear",
                     year_introduced=None),
    KnownApplication(sector="Coatings, Paints & Inks", derivative="Soy Oil", category="Anti-corrosion",
                     product_name=None, manufacturer=None,
                     description="Soy oil-modified epoxy anti-corrosion primers for steel infrastructure",
                     year_introduced=None),
    KnownApplication(sector="Pharmaceuticals & Medical", derivative="Soy Protein", category="Tissue engineering",
                     product_name=None, manufacturer=None,
                     description="Soy protein hydrogel scaffolds for cartilage and bone tissue engineering research",
                     year_introduced=None),
    KnownApplication(sector="Electronics", derivative="Soy Oil", category="Thermal interface",
                     product_name=None, manufacturer=None,
                     description="Soy oil-based thermal interface materials for electronic heat dissipation",
                     year_introduced=None),
]
